# Site settings
title: Re:Olympia
header-img: img/bg/skyline.jpg
email: admin@reolympia.com
description: "What's happening in Olympia, WA"
baseurl: ""
url: "https://reolympia.com"
twitter_username: richeee
instagram_username: reolympia
#github_username:  davidtmiller
#facebook_username:  IronSummitMedia
#email_username:  your-email@yourdomain.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
